---
date: "`r format(Sys.time(), '%B, %d %Y')`"
output:
  html_document:
    theme: united
    highlight: textmate
    code_folding: show
    toc: true
    toc_float: true
editor_options:
  chunk_output_type: inline
always_allow_html: yes
---

```{r Global-options, include=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.asp=.618, fig.align="center",
                      fig.path='Figs/', warning=FALSE, message=FALSE)
```

```{r Preamble, echo=FALSE}
# Enter package in p_load()
# If package is not installed, p_load() will install and load the package
if(!"pacman" %in% rownames(installed.packages())) {
  install.packages("pacman")
  }
pacman::p_load(tidyverse, ggthemes, here, purrr, furrr)

# Set default ggplot theme to tufte
theme_set(ggthemes::theme_tufte())
```

```{r }
myDenParams <- c(1, 1, 5, 5, .8)
```

```{r }
calc_z <- function(x, mu1, mu2, sigma1, sigma2, rho) {
  x1 <- x[1]
  x2 <- x[2]
  ((x1 - mu1)^2 / sigma1^2) - ((2 * rho * (x1 - mu1) * (x2 - mu2)) / (sigma1 * sigma2)) + ((x2 - mu2)^2 / (sigma2^2))
}

den <- function(argmts, params, sigProp) {
  x1 <- argmts[1]
  x2 <- argmts[2]
  mu1 <- params[1]
  mu2 <- params[2]
  sigma1 <- params[3]
  sigma2 <- params[4]
  rho <- params[5]
  (1 / (2 * pi * sigma1 * sigma2 * sqrt(1 - rho^2))) * exp(1)^((-calc_z(c(x1, x2), mu1, mu2, sigma1, sigma2, rho)) / (2 * (1 - rho^2)))
}

den(c(1, 1), myDenParams)
```

```{r }
oneStep <- function(denFun, initSt, denParams, sigProp) {
  new_proposal <- initSt + rnorm(2, mean = 0, sd = sigProp)
  initSt_probs <- denFun(initSt, denParams)
  new_proposal_probs <- denFun(new_proposal, denParams)
  
  if (new_proposal_probs > initSt_probs) {
    accept <- 1
  } else {
    p <- new_proposal_probs / initSt_probs
    accept <- sample(c(0, 1), 1, prob = c(1 - p, p))
  }
  
  data.frame(x1 = new_proposal[1], x2 = new_proposal[2], accept)
}
```

```{r }
run_mcmc <- function(iterations, init, sigProp) {
  result <-
    data.frame(
      x1 = vector("numeric", iterations),
      x2 = vector("numeric", iterations),
      accept = vector("numeric", iterations)
    )
  
  for (i in 1:iterations) {
    result[i, ] <- oneStep(den, init, myDenParams, sigProp)
    init <- switch(result$accept[[i]] + 1,
                   init,
                   c(result$x1[[i]], result$x2[[i]]))
  }
  
  result
}
```

```{r }
multi_start <- function(runs, iteration, seed, sd) {
  set.seed(seed)
  init <- rerun(length(runs), sample(-75:75, 2))
  
  plan(multiprocess)
  multi_result <- furrr::future_pmap(
    list(
      iterations = rep(iteration, each = length(runs)),
      init = init,
      sigProp = rep(sd, each = length(runs)),
      runs = runs
    ),
    function(iterations, init, sigProp, runs) {
      run_mcmc(iterations, init, sigProp) %>% 
        mutate(run = runs)
    })
  
  plot_all_data <- map(multi_result, ~ mutate(
    .x,
    accept = factor(
      accept,
      levels = c(0, 1),
      labels = c("Rejections", "Trajectory")
    )
  )) %>%
    bind_rows() %>% 
    filter(accept == "Trajectory") %>%
    mutate(run = factor(run))
  
  start <- plot_all_data %>% split(.$run) %>% map( ~ head(.x, 1)) %>% bind_rows()
  end <- plot_all_data %>% split(.$run) %>% map( ~ tail(.x, 1)) %>% bind_rows()
  list(plot_data = plot_all_data, start = start, end = end, sd = sd)
}

metropolis_grid <- function(param, runs, columns, iterations = NULL, sd_test = FALSE, default_sd = NULL, seed = NULL) {
  
  if (!sd_test & is.null(default_sd)) {
    stop("default_sd is NULL. Specification required for sd_test.")
  }
  
  sd <- default_sd
  
  if (sd_test) {
    subtitles <- glue::glue("Standard deviation: {param}")
    main_subtitle <- glue::glue("Iterations: {scales::comma(iterations)}")
  } else {
    subtitles <- glue::glue("Iterations: {scales::comma(param)}")
    main_subtitle <- glue::glue("Standard deviation: {sd}")
  }
  
  plan(multiprocess)
  if (sd_test) {
    results <-
      furrr::future_map(param, ~ multi_start(
                          runs,
                          iteration = iterations,
                          seed = seed,
                          sd = .x
                        ))
  } else {
    results <-
      furrr::future_map(param, ~ multi_start(
                          runs,
                          iteration = .x,
                          seed = seed,
                          sd = sd
                        ))
  }
  
  plots <- furrr::future_map2(results, subtitles, function(data, subtitles) {
    data$plot_data %>%
      ggplot(aes(x1, x2, color = run)) +
      geom_point(shape = 1) +
      geom_label(data = data$start, aes(x1, x2, label = glue::glue("Start {run}")), size = 2.5) +
      geom_label(data = data$end, aes(x1, x2, label = glue::glue("End {run}")), size = 2.5) +
      scale_color_viridis_d(guide = FALSE) +
      labs(title = NULL,
         subtitle = subtitles,
         x = NULL,
         y = NULL)
    }
  )
  
  title_grob <- grid::textGrob(
    label = glue::glue('Metropolis Rule: Normal Bivariate Distribution
    Accepted Proposal Path Random Starts: {length(runs)}
    {main_subtitle}'),
    x = unit(.5, "lines"), 
    y = unit(0, "lines"),
    hjust = 0, 
    vjust = 0,
    gp = grid::gpar(fontface = "bold"))
  
  grid_args <- c(plots, list(ncol = columns,
                             top = title_grob,
                             bottom = grid::textGrob("x1"),
                             left = grid::textGrob("x2", rot = 90, vjust = 1)))
  invoke(gridExtra::grid.arrange, grid_args)
}
```

```{r Plot-sd-grid, fig.width=10}
metropolis_grid(
  param = seq(.025, .4, .075),
  runs = 1:3,
  iterations = 1000,
  sd_test = TRUE,
  columns = 3,
  seed = 1
)

metropolis_grid(
  param = seq(seq(.025, .4, .075)[length(seq(.025, .4, .075))] + .075, .9, .075),
  runs = 1:3,
  iterations = 1000,
  sd_test = TRUE,
  columns = 3,
  seed = 1
)
```

```{r Plot-iteration-grid, fig.width=10}
metropolis_grid(
  param = seq(1000, 5000, 2000),
  default_sd = .05,
  runs = 1:3,
  columns = 3,
  seed = 1
)

metropolis_grid(
  param = seq(7000, 12000, 2000),
  default_sd = .05,
  runs = 1:3,
  columns = 3,
  seed = 1
)
```
