---
title: "Review Session 6"
author: "Joshua Goldberg"
date: "`r format(Sys.time(), '%B, %d %Y')`"
always_allow_html: yes
output:
  github_document: 
  pdf_document: default
editor_options: 
  chunk_output_type: inline
---

```{r Global-options, include=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/',
                      warning=FALSE, message=FALSE, cache=TRUE)
```

```{r Preamble, echo=FALSE}
# Enter package in p_load()
# If package is not installed, p_load() will install and load the package
if(!"pacman" %in% rownames(installed.packages())) {
  install.packages("pacman")
  }
pacman::p_load(tidyverse, ggthemes, here, rstan, foreign, HDInterval, tictoc, furrr, latex2exp)

# Set default ggplot theme to tufte
theme_set(ggthemes::theme_tufte())
```

```{r Copy-files, echo=FALSE, eval=FALSE}
# Enter files to load to project directory in from = "~/Downloads/your_file_name_here"
file.copy(from = "~/Downloads/", to = here::here(), 
          overwrite = TRUE, recursive = FALSE, 
          copy.mode = TRUE)
```

```{r}
child_data <- read.dta("ARM_Data/child.iq/kidiq.dta")
```

```{r}
child_data
```

```{r}
heights_data <- read.dta("ARM_Data/earnings/heights.dta")
heights_data %>% head()
```

```{r}
h_clean <- heights_data %>% na.omit() %>% filter(earn != 0)
```

```{r}
N <- nrow(h_clean)
earn <- h_clean$earn
height <- h_clean$height
```

```{r}
stan_rdump(c("N", "earn", "height"), file = "heights.data.R")
data <- read_rdump("heights.data.R")
map(data, ~ head(.x))
```

```{r}
fit <- stan(file = "review6_session_model1.stan", data = data, seed = 1)
```

```{r}
show(fit)
plot(fit)
```

```{r}
stan_dens(fit)
```

```{r}
fit_mean_c <- stan(file = "review6_session_model2.stan", data = data, seed = 1)
```

```{r}
plot(fit_mean_c)
```

```{r}
stan_dens(fit_mean_c)
show(fit_mean_c)
```

```{r}
fit_mean_c_priors <- stan(file = "review6_session_model3.stan", data = data, seed = 1)
```

```{r}
stan_dens(fit_mean_c_priors)
show(fit_mean_c_priors)
```

```{r}
N <- nrow(h_clean)
earn <- h_clean$earn
height <- h_clean$height
male <- h_clean$sex == 1

stan_rdump(c("N", "earn", "height", "male"), file = "heights.data.R")
data <- read_rdump("heights.data.R")
map(data, ~ head(.x))
```

```{r}
fit_mean_c_priors_male <- stan(file = "review6_session_model4.stan", data = data, seed = 1)
```

```{r}
stan_dens(fit_mean_c_priors_male)
show(fit_mean_c_priors_male)
```

If the output the loo object is position, `elpd_diff`, then the first model is better.
```{r}
library(loo)
log_lik_1 <- extract_log_lik(fit_mean_c_priors, "lp__", merge_chain = FALSE)
loo_1 <- loo(log_lik_1)

log_lik_2 <- extract_log_lik(fit_mean_c_priors_male, "lp__", merge_chain = FALSE)
loo_2 <- loo(log_lik_2)

compare(loo_1, loo_2)
```

```{r}
fit_mean_c_priors_male_interact <- stan(file = "review6_session_model5.stan", data = data, seed = 1)
```

```{r}
plot(fit_mean_c_priors_male_interact)
stan_dens(fit_mean_c_priors_male_interact)
show(fit_mean_c_priors_male_interact)
```







