---
title: "Untitled"
author: "Your Name"
date: "`r format(Sys.time(), '%B, %d %Y')`"
always_allow_html: yes
output:
  github_document: 
  pdf_document: default
editor_options: 
  chunk_output_type: inline
---

```{r Global-options, include=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/',
                      warning=FALSE, message=FALSE, cache=TRUE)
```

```{r Preamble, echo=FALSE}
# Enter package in p_load()
# If package is not installed, p_load() will install and load the package
if(!"pacman" %in% rownames(installed.packages())) {
  install.packages("pacman")
  }
pacman::p_load(tidyverse, ggthemes, here)

# Set default ggplot theme to tufte
theme_set(ggthemes::theme_tufte())
```

```{r Copy-files, echo=FALSE, eval=FALSE}
# Enter files to load to project directory in from = "~/Downloads/your_file_name_here"
file.copy(from = "~/Downloads/", to = here::here(), 
          overwrite = TRUE, recursive = FALSE, 
          copy.mode = TRUE)
```

# 1 References

# 2 Review of binomial model
```{r}
omega <- .05
kappa <- 100
a <- omega * (kappa - 2) + 1
b <- (1 - omega) * (kappa - 2) + 1
```

```{r}
x <- seq(from = 0, to = 1, by = .001)
priorBetaDens <- dbeta(x, shape1 = a, shape2 = b)
plot(x, priorBetaDens, type = 'l', lwd = 3)
abline(v = .05)
```

```{r}
(smple <- c(rep(0, times = 92), rep(1, times = 8)))
(k <- sum(smple))
postA <- k + a
postB <- s - k + b
(s <- length(smple))
posteriorBetaDens <- dbeta(x, shape1 = postA, shape2 = postB)

postA <- k + a
postB <- s - k + b
posteriorBetaDens <- dbeta(x, shape1 = postA, shape2 = postB)

plot(
  x,
  priorBetaDens,
  type = 'l',
  lwd = 3,
  col = 'blue',
  ylim = c(0, 25),
  xlim = c(0, .2)
)
lines(x, posteriorBetaDens, lwd = 3, col = 'orange')
legend(
  "topright",
  legend = c("prior", "posterior"),
  col = c("blue", "orange"),
  lwd = 3
)
```

```{r}
(muPosterior <- postA / (postA + postB))
# New concentration
(kappaPosterior <- postA + postB)
```

# 3 Exchangeability and sampling

# 4 Binomial Model with hyperparameters
```{r}
Omega <- Theta <- seq(0 , 1 , length = 101)
plot(Omega, dbeta(Omega, 2, 2))
```

```{r}
A_omega <- 2
B_omega <- 2
K <- 100

jointPrior <- function(theta, omega, A_omega, B_omega, K) {
  res <-
    dbeta(omega, A_omega, B_omega) * dbeta(theta, omega * (K - 2) + 1, (1 - omega) * (K - 2) + 1)
  res
}
```

```{r}
dens <- expand.grid(Omega, Theta)
colnames(dens) <- c("Omega", "Theta")
dens$Prior <- apply(dens, 1, function(z) jointPrior(z[1], z[2], A_omega, B_omega, K))
Prior.theta.omega <- matrix(dens$Prior, 101, 101)
Prior.theta.omega <- Prior.theta.omega / sum(Prior.theta.omega) # Joint prior
Prior.omega.marginal <- apply(Prior.theta.omega, 2, sum)
Prior.omega.marginal <- Prior.omega.marginal / sum(Prior.omega.marginal) * 100 # Omega marginal prior

matplot(Omega,
        cbind(Prior.omega.marginal, dbeta(Omega, A_omega, B_omega)),
        type = "l",
        ylab = "Marginal p(omega)")
```

```{r}
likeli <- function(theta, s, k) {
  theta^k * (1 - theta)^(s - k)
}

likelihood <- likeli(Theta, 12, 9)

plot(Theta,
     likelihood,
     type = "l",
     ylab = "p(y|theta)",
     main = "Likelihood")
```

```{r}
Posterior <- apply(Prior.theta.omega, 2, function(z) z * likelihood)
Posterior <- Posterior / sum(Posterior)
```

```{r}
A_omega <- 20
B_omega <- 20
K <- 6
```

```{r}
jointPrior <- function(theta, omega, A_omega, B_omega, K) {
  res <-
    dbeta(omega, A_omega, B_omega) * dbeta(theta, omega * (K - 2) + 1, (1 - omega) * (K - 2) + 1)
  res
}
```

```{r}
dens <- expand.grid(Omega, Theta)
colnames(dens) <- c("Omega", "Theta")
dens$Prior <- apply(dens, 1, function(z) jointPrior(z[1], z[2], A_omega, B_omega, K))
Prior.theta.omega <- matrix(dens$Prior, 101, 101)
Prior.theta.omega <- Prior.theta.omega / sum(Prior.theta.omega) #Joint prior
Prior.omega.marginal <- apply(Prior.theta.omega, 2, sum)
Prior.omega.marginal <- Prior.omega.marginal / sum(Prior.omega.marginal) * 100 #Omega marginal prior
matplot(Omega,
        cbind(Prior.omega.marginal, dbeta(Omega, A_omega, B_omega)),
        type = "l",
        ylab = "Marginal p(omega)")
```

```{r}
Prior.theta.marginal <- apply(Prior.theta.omega, 1, sum)
Prior.theta.marginal <- Prior.theta.marginal / sum(Prior.theta.marginal) * 100 #Theta marginal prior
plot(Theta, Prior.theta.marginal, type = "l", ylab = "Marginal p(theta)")
```

```{r}
persp(
  Theta,
  Omega,
  Prior.theta.omega,
  d = 1,
  theta = -25,
  phi = 20,
  main = "Joint Prior Distribution"
)

contour(
  x = Omega,
  y = Theta,
  z = Prior.theta.omega,
  ylab = "omega",
  xlab = "theta",
  main = "Joint Prior Distribution"
)

par(mfrow = c(3, 1))
Prior.theta.omega.25 <- jointPrior(Theta, 0.25, A_omega, B_omega, K)
Prior.theta.omega.25 <-
  Prior.theta.omega.25 / sum(Prior.theta.omega.25) * 100
plot(
  Theta,
  Prior.theta.omega.25,
  type = "l",
  ylab = "p(theta|omega=0.25)",
  main = "Marginal prior for Theta"
)
Prior.theta.omega.5 <- jointPrior(Theta, 0.5, A_omega, B_omega, K)
Prior.theta.omega.5 <- Prior.theta.omega.5 / sum(Prior.theta.omega.5) * 100
plot(Theta, Prior.theta.omega.5, type = "l", ylab = "p(theta|omega=0.5)")
Prior.theta.omega.75 <- jointPrior(Theta, 0.75, A_omega, B_omega, K)
Prior.theta.omega.75 <- Prior.theta.omega.75 / sum(Prior.theta.omega.75) * 100
plot(Theta, Prior.theta.omega.75, type = "l", ylab = "p(theta|omega=0.75)")
```

```{r}
likelihood <- likeli(Theta, 12, 9)
plot(Theta,
     likelihood,
     type = "l",
     ylab = "p(y|theta)",
     main = "Likelihood")
```

```{r}
Posterior <- apply(Prior.theta.omega, 2, function(z) z * likelihood)
Posterior <- Posterior / sum(Posterior)
```

```{r}
persp(
  Theta,
  Omega,
  Posterior,
  d = 1,
  theta = -25,
  phi = 20,
  main = "Joint Posterior Distribution"
)

contour(
  x = Omega,
  y = Theta,
  z = Posterior,
  ylab = "omega",
  xlab = "theta",
  main = "Joint Posterior Distribution"
)
```

```{r}
Posterior.omega.marginal <- apply(Posterior, 2, sum)
Posterior.omega.marginal <- Posterior.omega.marginal / sum(Posterior.omega.marginal) * 100
plot(Omega, Posterior.omega.marginal, type = "l")
```

```{r}

```

